# Generated by Django 5.0 on 2023-12-12 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_review', '0005_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='image',
            field=models.ImageField(default='', upload_to='images/'),
        ),
        migrations.DeleteModel(
            name='TicketImage',
        ),
    ]
