# Generated by Django 5.0 on 2023-12-14 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_review', '0011_alter_ticket_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
