# Generated by Django 5.0 on 2023-12-21 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_review', '0014_ticket_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='image',
            field=models.ImageField(default='', upload_to='static//images/'),
        ),
    ]
