# Generated by Django 5.0 on 2023-12-29 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_review', '0018_alter_review_time_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='image',
            field=models.ImageField(default='', upload_to='static//images/'),
        ),
    ]
