# Generated by Django 5.0 on 2023-12-29 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_review', '0019_review_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
