# Generated by Django 5.0 on 2024-01-04 09:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_review', '0020_alter_review_image_alter_ticket_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='time_created',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 1, 4, 9, 42, 47, 446265)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 1, 4, 9, 42, 47, 445888)),
        ),
    ]
