# Generated by Django 5.0 on 2024-01-04 13:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_review', '0022_alter_review_ticket_alter_review_time_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 4, 13, 57, 49, 138620)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 4, 13, 57, 49, 138267)),
        ),
    ]
