# Generated by Django 5.0 on 2024-03-30 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_review', '0026_alter_review_ticket_alter_review_time_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='title',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='content',
            field=models.TextField(default='', max_length=2048),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='title',
            field=models.CharField(default='', max_length=128),
        ),
    ]
