# Generated by Django 5.0 on 2024-03-30 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_review', '0027_review_title_alter_ticket_content_alter_ticket_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='content',
            field=models.TextField(default='', max_length=2048),
        ),
        migrations.AlterField(
            model_name='review',
            name='image',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
