# Generated by Django 3.1.4 on 2023-12-07 16:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manage_user', '0005_auto_20231207_1626'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AuthenticationInfo',
            new_name='Authenticate',
        ),
    ]
