# Generated by Django 3.1.4 on 2023-12-07 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_user', '0006_auto_20231207_1627'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Authenticate',
        ),
    ]
