# Generated by Django 5.0 on 2023-12-12 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_user', '0007_delete_authenticate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfollows',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
