# Generated by Django 5.0 on 2023-12-28 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_user', '0009_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
